### ISSUE TITLE
Формы 101, 102, 123, 134, 135

### ISSUE THREAD

**Issue by dreddsa5dies** [zx48/cbr#1]
Прошу помощи в получении форм 101, 102, 123, 134, 135 с cbr.ru

**Comment by zx48** [comment]
Я не специалист в банковском деле, поэтому номера форм мне ничего не скажут. То что я реализовал - это сервис http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx . Могу лишь посоветовать начать поиск с http://www.cbr.ru/scripts/Root.asp

**Comment by dreddsa5dies** [comment]
Алексей, спасибо за внимание. 
Я хотел Вашей консультации как мне реализовать сервис http://www.cbr.ru/CreditInfoWebServ/CreditOrgInfo.asmx на Go. Вот там как раз эти формы.

**Comment by zx48** [comment]
Добавил пример реализации одного метода для наглядности

**Comment by dreddsa5dies** [comment]
Спасибо.
